### PR TITLE
Add link to W3C editors’ draft

### PR DESCRIPTION
**Pull request by jsynowiec**
A public copy of the editors’ draft, a living document addressing new features including foreign fetch and header-based installation, etc.

### CODE REVIEW

**Comment by TalAter** [comment]
I don't know about this one... I think we should keep the list more lean - curated. Is there a benefit for looking at the working draft for the common developer using service workers?

What do you think?

**Comment by jsynowiec** [comment]
This draft is the most up-to-date version. There are even changes from a few days ago and some proposed enhancements look interesting. Personally I like to keep track of what is happening and what might come in the future.

**Comment by TalAter** [comment]
It is certainly interesting for the hardcore among us, but I don't see how this is a must read resource for everyone else

**Comment by jsynowiec** [comment]
I thought we are gathering valuable resources, not 'must read' for general public ;-) But it's your call. I have some more guides to add later today. Maybe those are better.

**Comment by TalAter** [comment]
I think the power of these lists is in being highly curated, not exhaustive. They should contain only the absolute must read resources (for the different levels)... I think if we are in doubt about whether something should be on the list or not, then maybe it shouldn't.

**Pull request closed without merging**
